
'use client';

import type { NextPage } from 'next';
import Head from 'next/head';

import { useAccount } from "wagmi";
import { useState, useEffect } from "react";
import { AccountForm } from '@/components/account';


const Account: NextPage = () => {

  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);


  return (
    <div>
      <Head>
        <title>Account</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>

      <div className="space-y-6 my-8 mx-16">
        <AccountForm />
      </div>
        
      </main>

    </div>
  );
};

export default Account;
